"""empty message

Revision ID: c35f75d42c8c
Revises: e2211f94f78e
Create Date: 2018-06-29 11:30:21.705757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c35f75d42c8c'
down_revision = 'e2211f94f78e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fname')
    op.drop_column('users', 'lname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('fname', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
